-- =====================================================================
-- ROLLBACK de integración CORONELBOT
-- ADVERTENCIA: elimina la bitácora y metadatos de integración.
-- No elimina vales ni productos operativos ya creados.
-- Respaldar la base antes de ejecutar.
-- =====================================================================

SET NAMES utf8mb4;
SET SQL_SAFE_UPDATES = 0;

DROP TABLE IF EXISTS rebanado_sync_runs;

SET @exists := (SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'vale_productos' AND INDEX_NAME = 'uq_vale_productos_external_line_key');
SET @sql := IF(@exists > 0, 'ALTER TABLE vale_productos DROP INDEX uq_vale_productos_external_line_key', 'SELECT ''Índice de línea ya no existe'' AS info'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @exists := (SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'vale_productos' AND INDEX_NAME = 'idx_vale_productos_sap_line');
SET @sql := IF(@exists > 0, 'ALTER TABLE vale_productos DROP INDEX idx_vale_productos_sap_line', 'SELECT ''Índice SAP de línea ya no existe'' AS info'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @exists := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'vale_productos' AND COLUMN_NAME = 'last_synced_at'); SET @sql := IF(@exists > 0, 'ALTER TABLE vale_productos DROP COLUMN last_synced_at', 'SELECT ''last_synced_at ya no existe'' AS info'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @exists := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'vale_productos' AND COLUMN_NAME = 'almacen'); SET @sql := IF(@exists > 0, 'ALTER TABLE vale_productos DROP COLUMN almacen', 'SELECT ''almacen ya no existe'' AS info'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @exists := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'vale_productos' AND COLUMN_NAME = 'external_line_key'); SET @sql := IF(@exists > 0, 'ALTER TABLE vale_productos DROP COLUMN external_line_key', 'SELECT ''external_line_key ya no existe'' AS info'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @exists := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'vale_productos' AND COLUMN_NAME = 'sap_line_num'); SET @sql := IF(@exists > 0, 'ALTER TABLE vale_productos DROP COLUMN sap_line_num', 'SELECT ''sap_line_num ya no existe'' AS info'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- Convierte tipos no estándar a Otro antes de restaurar el ENUM original.
UPDATE vale_productos SET tipo_rebanado = 'Otro' WHERE tipo_rebanado NOT IN ('Estándar','Grueso','Otro');
UPDATE vale_productos SET presentacion = LEFT(presentacion, 50) WHERE CHAR_LENGTH(presentacion) > 50;
ALTER TABLE vale_productos MODIFY COLUMN presentacion VARCHAR(50) NOT NULL;
ALTER TABLE vale_productos MODIFY COLUMN tipo_rebanado ENUM('Estándar','Grueso','Otro') NOT NULL DEFAULT 'Estándar';

SET @exists := (SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'vales' AND INDEX_NAME = 'uq_vales_external_key'); SET @sql := IF(@exists > 0, 'ALTER TABLE vales DROP INDEX uq_vales_external_key', 'SELECT ''Índice external_key ya no existe'' AS info'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @exists := (SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'vales' AND INDEX_NAME = 'idx_vales_sap_docentry'); SET @sql := IF(@exists > 0, 'ALTER TABLE vales DROP INDEX idx_vales_sap_docentry', 'SELECT ''Índice sap_docentry ya no existe'' AS info'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @column_name := 'last_synced_at'; SET @exists := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'vales' AND COLUMN_NAME = @column_name); SET @sql := IF(@exists > 0, CONCAT('ALTER TABLE vales DROP COLUMN ', @column_name), 'SELECT ''columna ya no existe'' AS info'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @column_name := 'siclik_usuario_correo'; SET @exists := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'vales' AND COLUMN_NAME = @column_name); SET @sql := IF(@exists > 0, CONCAT('ALTER TABLE vales DROP COLUMN ', @column_name), 'SELECT ''columna ya no existe'' AS info'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @column_name := 'siclik_usuario_nombre'; SET @exists := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'vales' AND COLUMN_NAME = @column_name); SET @sql := IF(@exists > 0, CONCAT('ALTER TABLE vales DROP COLUMN ', @column_name), 'SELECT ''columna ya no existe'' AS info'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @column_name := 'numero_traslado'; SET @exists := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'vales' AND COLUMN_NAME = @column_name); SET @sql := IF(@exists > 0, CONCAT('ALTER TABLE vales DROP COLUMN ', @column_name), 'SELECT ''columna ya no existe'' AS info'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @column_name := 'comentario_entrega'; SET @exists := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'vales' AND COLUMN_NAME = @column_name); SET @sql := IF(@exists > 0, CONCAT('ALTER TABLE vales DROP COLUMN ', @column_name), 'SELECT ''columna ya no existe'' AS info'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @column_name := 'entrega_epp'; SET @exists := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'vales' AND COLUMN_NAME = @column_name); SET @sql := IF(@exists > 0, CONCAT('ALTER TABLE vales DROP COLUMN ', @column_name), 'SELECT ''columna ya no existe'' AS info'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @column_name := 'entrega_nombre'; SET @exists := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'vales' AND COLUMN_NAME = @column_name); SET @sql := IF(@exists > 0, CONCAT('ALTER TABLE vales DROP COLUMN ', @column_name), 'SELECT ''columna ya no existe'' AS info'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @column_name := 'entrega_horario'; SET @exists := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'vales' AND COLUMN_NAME = @column_name); SET @sql := IF(@exists > 0, CONCAT('ALTER TABLE vales DROP COLUMN ', @column_name), 'SELECT ''columna ya no existe'' AS info'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @column_name := 'entrega_fecha_fin'; SET @exists := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'vales' AND COLUMN_NAME = @column_name); SET @sql := IF(@exists > 0, CONCAT('ALTER TABLE vales DROP COLUMN ', @column_name), 'SELECT ''columna ya no existe'' AS info'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @column_name := 'entrega_fecha_inicio'; SET @exists := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'vales' AND COLUMN_NAME = @column_name); SET @sql := IF(@exists > 0, CONCAT('ALTER TABLE vales DROP COLUMN ', @column_name), 'SELECT ''columna ya no existe'' AS info'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @column_name := 'entrega_dias_texto'; SET @exists := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'vales' AND COLUMN_NAME = @column_name); SET @sql := IF(@exists > 0, CONCAT('ALTER TABLE vales DROP COLUMN ', @column_name), 'SELECT ''columna ya no existe'' AS info'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @column_name := 'fecha_pedido'; SET @exists := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'vales' AND COLUMN_NAME = @column_name); SET @sql := IF(@exists > 0, CONCAT('ALTER TABLE vales DROP COLUMN ', @column_name), 'SELECT ''columna ya no existe'' AS info'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @column_name := 'cliente_codigo'; SET @exists := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'vales' AND COLUMN_NAME = @column_name); SET @sql := IF(@exists > 0, CONCAT('ALTER TABLE vales DROP COLUMN ', @column_name), 'SELECT ''columna ya no existe'' AS info'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @column_name := 'external_key'; SET @exists := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'vales' AND COLUMN_NAME = @column_name); SET @sql := IF(@exists > 0, CONCAT('ALTER TABLE vales DROP COLUMN ', @column_name), 'SELECT ''columna ya no existe'' AS info'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @column_name := 'sap_docnum'; SET @exists := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'vales' AND COLUMN_NAME = @column_name); SET @sql := IF(@exists > 0, CONCAT('ALTER TABLE vales DROP COLUMN ', @column_name), 'SELECT ''columna ya no existe'' AS info'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @column_name := 'sap_docentry'; SET @exists := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'vales' AND COLUMN_NAME = @column_name); SET @sql := IF(@exists > 0, CONCAT('ALTER TABLE vales DROP COLUMN ', @column_name), 'SELECT ''columna ya no existe'' AS info'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET SQL_SAFE_UPDATES = 1;
SELECT 'Rollback CORONELBOT aplicado; vales y productos operativos fueron conservados' AS resultado;
